### ISSUE TITLE
option for add .gitignore

### ISSUE THREAD

**Issue by romqin** [symfony/symfony-installer#102]
Hello,

Could we add an option to have the `.gitignore` ?
What do you think ?

**Comment by javiereguiluz** [comment]
@romqin thanks for your proposal. Not only we think that you are right, but we even think that this should not be an option but something mandatory.

The problem is that we don't want to do this change in the installer because we think it's better to do this change when we prepare the ZIP/TGZ packages stored on symfony.com and used by the installer. In fact, we're going to implement all the changes suggested by @lyrixx in this issue: https://github.com/symfony/symfony-installer/issues/73

**Comment by romqin** [comment]
Nice ! Thanks @javiereguiluz.
