### ISSUE TITLE
Installer parameter: install without Acme

### ISSUE THREAD

**Issue by radekwaszczuk** [symfony/symfony-installer#115]

**Comment by javiereguiluz** [comment]
@radekwaszczuk I agree with you. I've opened a related pull request here to remove the `AcmeDemoBundle` from the installed Symfony version: https://github.com/sensiolabs/SensioDistributionBundle/pull/198

**Comment by zomberg** [comment]
+1

**Comment by darraghenright** [comment]
+1

**Comment by ByScripts** [comment]
I'm OK with that too

**Comment by javiereguiluz** [comment]
I'm closing this issue because this is becoming a reality. Starting from the next Symfony versions, the AcmeDemoBundle will never be included. Instead, we've developed a separate full-featured Symfony Demo application that will be used to learn Symfony.

So the AcmeDemoBundle is gone forever .... but you still see it until we release new Symfony versions.
