### ISSUE TITLE
Installation of dev/beta versions

### ISSUE THREAD

**Issue by xelaris** [symfony/symfony-installer#143]
I wonder if `http://get.symfony.com/Symfony_Standard_Vendors_2.7.0-dev.tgz` should be available or the installer should not try to fetch it. When calling `symfony new blog 2.7`, version 2.7 is resolved to `2.7.0-dev`, since it is provided so by http://symfony.com/versions.json, so the installer tries to fetch the file and stops with "The selected version (2.7.0-dev) cannot be installed because it does not exist.".
Maybe the installer should respect the list of `installable` versions, provided by `versions.json`, or forbid "branch-versions" in general?
Further, if it should be possible to install 2.7 with the installer, I would expect to get `2.7.0-beta1` now.

I guess it is not intended to enable installation of dev/beta versions? Then, what about providing a message like:

> You are trying to install an unstable version. Please use composer to install such versions:
>
> $ composer create-project symfony/framework-standard-edition blog (at)beta
>

**Comment by Pierstoval** [comment]
I think it's not intended to enable installation of unstable(like dev or beta) versions.
 
To use SF 2.7, just install 2.6 with `symfony new project 2.6` and change your composer.json file to fetch `~2.7@beta` version.

**Comment by javiereguiluz** [comment]
@xelaris thanks for opening this issue. I think it's an interesting discussion and I have no clear answer.

My opinion is that we should only install stable versions ... but I'm totally open to hear other people's opinions about this.

And I agree with your proposal of showing a message if the user tries to install a `dev` version. The problem is, how can we detect correctly that it's a `dev` version? If the user writes exactly `2.7.0-dev`, we can detect that; but if the user writes `2.7`, I don't know how can we detect that.

**Comment by Pierstoval** [comment]
Technically, a `dev` version is any version tag matching `x.y.z` under the `dev` key in the [versions.json](http://symfony.com/versions.json) file, isn't it?

**Comment by stof** [comment]
@javiereguiluz if he writes 2.7, you are asking symfony.com for the exact version, right ? This means you can detect the dev version after that too.

**Comment by xelaris** [comment]
Like @stof said, after resolving 2.7 via the `versions.json` it is possible to check the version for a 'dev' and/or 'beta' postfix and provide such a message. I have opened a related PR.
