### ISSUE TITLE
symfony installer does not leave a composer executable after install

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony-installer#171]
see https://github.com/we-bridge/vagrant-ansible-symfony/issues/5

basically the goal of the symfony installer is to be able to create a project without needing to use composer however, it uses a composer.json, so using it instead of composer to init a new projet still require at the end of the day to have composer 

so open question,  if no composer are in the $PATH, shouldn't be symfony installer job to make sure there's one (even just in the project's root) ?

**Comment by Pierstoval** [comment]
I think it makes sense to check for a composer installation in the $PATH, but IMO, downloading it is not the best solution. I think a simple message after installing Symfony might be good, just providing the full command to install composer.

**Comment by allan-simon** [comment]
actually does the symfony installer not already download a copy of composer ? because at the end of the day symfony installer does install the dependency for you (from the composer.json no?)

**Comment by Pierstoval** [comment]
No, the Symfony Installer just downloads a zipball from `get.symfony.com`, the same you get when downloading "Symfony with vendors" on the website. So the app is already "compiled", and the installer adds/removes some stuff to make the app more "personal". For example, it updates the `composer.json` file to change the project license and name, changing `symfony/symfony-standard` into `{your-name}/{your-project-name}`, it removes some markdown files, generates the `secret` parameter for you, etc.
 
Actually, composer is *not* needed to run a Symfony project. It's only mandatory if you want to add new dependencies and/or update the different components :)

**Comment by allan-simon** [comment]
I see, thanks for the clarifications

**Comment by javiereguiluz** [comment]
@allan-simon as explained by @Pierstoval the Symfony Installer doesn't use Composer. Instead of being a drawback, this is one of its best features. This allows us to install Symfony almost anywhere, whereas Composer requires some elements which are not always present (at least on Windows, which always caused troubles for us in the Symfony trainings).

In the past some people asked about adding support for installing Composer with the Symfony Installer. But we decided to not do that to maintain the focus of the installer. So I must close this proposal as *"won't fix"* (at least for now).

In any case, I'm not worried about not integrating Composer. My reasoning (which can be wrong of course) is the following:

  * If you know something about modern PHP, you probably have Composer already installed globally in your system.
  * If you know nothing about modern PHP, you probably don't know what is Composer and why you should use it. So if the installer proposes you to install Composer, you probably won't understand anything.

**Comment by Pierstoval** [comment]
@javiereguiluz If you know nothing about modern PHP, then you should never start with Symfony alone, so one day you'll know what Composer is, maybe before knowing to work with Symfony

**Comment by allan-simon** [comment]
for training purpose that does not go beyond the introduction,  i may understand,  but actually if you see the linked ticket,  we open this issue for the exact reason that during training session, where first present the symfony installer as "this way no need for composer" and as soon as you reach the chapter "update your dependencies to be sure to have latest security fix" or the chapter "connect with a database using doctrine"  ,   "errr so we're going to install composer"  and then people raise their hands "errr didn't what did you say during the first chapter already"

**Comment by javiereguiluz** [comment]
@allan-simon I understand your situation. However, if I may add something, I think that Composer is no longer "a PHP tool". To me, Composer is as essential as PHP itself. That's why I think that a computer without Composer installed globally is not ready to develop PHP applications. (By the way, the same goes for PHPUnit).

**Comment by Pierstoval** [comment]
I don't understand why you would need composer to use doctrine, it's bundled by default in the installer.
 
Actually, in trainings, you should talk about Composer much before talking about Symfony, because Composer is used on many other projects. A lot of applications that were once "download-zip-only" are moving into a "composer installable" system, because Composer is so awesome that a single file can manage all your dependencies. Plus, you can use Composer as a big starter to Symfony, thanks to the Silex framework that reproduces many features of Symfony (of course you'll need more time then). 
Actually, even if the team's policy is not to bundle Composer with Symfony (because Composer is mostly ought to be used globally, like the installer), you should already know about Composer before using Symfony.
The basics of Composer are namespaces, PSR-0 and PSR-4. These could be a great entry point to advanced PHP OOP programming and dependencies system.

**Comment by cbrunnkvist** [comment]
@javiereguiluz "composer cannot be reliably used on windows", are you referring to the fact that the windows PHP installer does not come out of the box with any SSL extension? 

(The effect is that _either_ it requires the user to go make a second download, locate the php_openssl.dll and enable it in php.ini, _OR_ you are left with a composer executable that might blow up as soon as it encounters a package distributed over an https-URL)

**Comment by cbrunnkvist** [comment]
@Pierstoval if you what you are saying about the "tacit knowledge dependency" (symfony->composer->php) is true, then the Symfony web page is wrong or misleading because it recommends using this fancy installer that bypasses composer.

@javier if you teach your class from the start to use a DVCS such as git, we end up with a broken Symfony app since `/app/bootstrap.php.cache` is (correctly, I might add) in the `.gitignore` produced by the installer. (-Anyone who runs git clone or git clean will be unable to proceed without intervention)

**Comment by Pierstoval** [comment]
You're partially right when saying that the Symfony web page is wrong because it recommends the installer. Actually, the only "wrong" part would be that the doc "forgets" to say that the knowledge of composer is very important (because without Composer you probably wouldn't know about autoloading, which is the core feature of Composer right before using Symfony. But still, Composer is a part of Symfony so one day it'll become mandatory for any user to know how it works. You wouldn't rent a dedicated web server yourself without knowing the use of `aptitude` or `yum`?
 
For the use of `git` and the `app/bootstrap.php.cache` , clearly, if you clone the standard edition, it's clearly normal that this file is git-ignored. The bootstrap file is a shortcut (as well as the `app/cache/{env}/classes.php` file) to improve performance by rewriting most used classes/namespaces so they are not autoloaded. This file is generated after a `composer install` or a `composer update`. So, with the installer, you never care about this file.
Whereas cloning the repo with git forces you to install Composer dependencies, so obviously your app will not run if you don't install them, and the bootstrap file depends on Composer.
