### ISSUE TITLE
Check downloaded file integrity

### ISSUE THREAD

**Issue by raulfraile** [symfony/symfony-installer#21]
Now, the Symfony installer downloads the compressed file from `http://symfony.com/download?v=Symfony_Standard_Vendors.x.x.x.zip`. As it is not using https, it would be safer if the installer could check the integrity of the downloaded file to avoid [man-in-the-middle attacks](https://en.wikipedia.org/wiki/Man-in-the-middle_attack). I am not sure if it is the best approach, but here goes my proposal:
1. With each compressed file, provide a separate file (e.g. Symfony_Standard_Vendors_2.5.5.key) with the hash of the file (e.g. hash256). That file should be [signed using the symfony.com private key](https://en.wikipedia.org/wiki/Public-key_cryptography#Inverse_Public_Key_Encryption).
2. In the installer, once the file has been downloaded and before doing any other operation, download the *.key file and decrypt it using the symfony.com public key. The public key would be included in the installer.
3. Check the integrity of the downloaded file (hashes are the same).

I know Composer is doing something similar, it would be nice to get some feedback.

**Comment by fstoerkle** [comment]
+1 on TLS support at least for the install URL

**Comment by jrobeson** [comment]
yes please. This is actually kinda a big deal :)

**Comment by sstok** [comment]
Only when the installer is provided over a secure connection, and is verifiable (not modified) its possible to use the signature provided by the install. TLS is only a part in that.

@padraic actually wrote a good blogpost about that http://blog.astrumfutura.com/2015/03/securely-distributing-phars-pitfalls-and-solutions/

We have to cut the breach a some point. OpenSSL is already available on Linux, for Windows its also very simple to enable this. If your hosting doesn't support SSL complain to enable this or get a better (read: real) hosting.

**Comment by padraic** [comment]
Openssl comes up a lot in avoiding signed packages and TLS because it will "make things harder for users". Never mind everyone who can't touch it with a barge pole because it's an obvious security vulnerability in the OWASP Top 10 that makes the internet explode with articles when it happens anywhere else. Other than openssl, one could feasibly switch to curl if present. This stuff all has fairly simple solutions. I spent more time writing the article.

The installer/hosting obeys not a single step I outlined in that article. 0/6 on the security scale. As a score, that just means it should not even exist as advertised. Nobody should be instructing users to download code from unsecure locations. The only way of getting it securely, at present, would be to simply clone it right off Github (ssh/https backed).

I also see the self-update command. If TLS is adopted, that would need to be updated to enforce TLS verification on versions <PHP 5.6.

My weekly sermon thus endeth ;).

**Comment by javiereguiluz** [comment]
I want to solve this issue but I'm not smart enough to do it. That's why I need your help.

### The problem to solve

We want to verify that the downloaded ZIP/TGZ package is the original one and therefore, it hasn't been modified by a malicious user.

### The conditions to meet by the verification process

  * It must be transparent to the user (no questions to answer and no commands to execute).
  * It must work perfectly on Linux, Mac and Windows.
  * It must not use OpenSSL (because it's unavailable for most Windows users).
  * It must not depend on Composer (the installer must be able to install Symfony without requiring the use of Composer)
  * (Optional) It shouldn't degrade the installer performance.

### What I ask from you

  * Resources that explain in practice and step-by-step how to solve this problem while meeting the above conditions.

Thanks!

**Comment by raulfraile** [comment]
I am not a security expert, so I may be wrong, but reading @padraic's post I think at least these two steps are required:

1. The installer must be distributed over HTTPS.
2. zip/tgz files must be downloaded over HTTPS enforcing TLS verification.

That means that `OpenSSL` should be available at least to download zip/tgz files securely. Also, HTTPS support in `symfony.com`.

What about Windows users without `OpenSSL`? The installer can still be downloaded over HTTPS (changing the instructions to not use PHP with readfile()) and zip/tgz files could be downloaded over HTTP displaying a warning with optional instructions to install `OpenSSL`.

Alternatively, would it be possible to use [PowerShell](https://teusje.wordpress.com/2011/02/19/download-file-with-powershell/) (preinstalled in W7 and W8) to download the zip/tgz files over HTTPS? For Unix-like systems users without OpenSSL, `curl` or `wget` could still be used.

**Comment by padraic** [comment]
@javiereguiluz Either you have openssl or curl, or HTTPS is not possible. If HTTPS is not possible, then you're already on the rocks. We're talking about PHP here - making remote requests is a basic operation and basic security like TLS is expected. If PHP exists with that capacity, then it's simply broken and needs to be fixed.

**Comment by javiereguiluz** [comment]
@padraic thanks to your comment I've just realized that cURL is also a no go because most Windows users don't have it. So I've just updated the list of conditions to add a new one. Thanks!

**Comment by raulfraile** [comment]
@javiereguiluz @padraic sorry to insist, but as I mentioned earlier, it is possible to download files over HTTPS using [PowerShell](http://en.wikipedia.org/wiki/Windows_PowerShell) in Windows systems, so cURL would not be necessary. It can be used as a fallback for OpenSSL.

**Comment by padraic** [comment]
@raulfraile Under Powershell, you can use the .NET WebClient class. Technically, via a script but you write it in a single line. As far as I'm aware it's TLS enabled out of the box.

**Comment by ircmaxell** [comment]
Enforcing TLS is only part of the problem. The other part is verifying that the release is what the author intends. If an attacker is able to gain access to symfony.com then they could forge the package and TLS won't help at all.

Instead, I think both TLS and package signing using GPG is required. But if you can have only one, it's GPG as it's more robust and protects against more attack vectors..

**Comment by weaverryan** [comment]
Thanks for chiming in @ircmaxell :).

I have a more broad question (which you might be able to help with) - has Composer even solved this totally?

1) They *are* coming over SSL (https://getcomposer.org/installer). It seems like we could mimic their installer script to also get SSL. I realize Windows users have an MSI installer, but I've also seen a number of windows users use the `fopen` solution too without a problem. Does that work for everyone?

2) Is Composer signing? I don't think they are per composer/composer#2665. If the whole PHP community hasn't figured it out for Composer, then I don't think we can either. There was a suggestion near the bottom of that thread, which was to download directly from GitHub - basically since that would be a highly-trusted server (but still not signed). Releases on GitHub *can* now include Phar files (see https://github.com/guzzle/guzzle/releases).

Javier - I like your requirements list above, but we should also make sure we're not trying to do the impossible.

Thanks!

**Comment by ircmaxell** [comment]
@weaverryan I'm not familiar with the fopen solution they are using. As to composer signing, that's a big thing that people are still working on support for.

**Comment by padraic** [comment]
@weaverryan Don't use installers. The reason I don't like them is that they are pigeon holing people into supporting the lowest common insecure denominator because the installer is a requirement. Required, but...the installer doesn't even install. It's a relatively simple script to check if the PHAR can run which then downloads a PHAR...usually insecurely.

I fixed the Composer installer to enforce TLS (so it's actually an exception), but it's still not a great solution. Standard security advice to disable `allow_url_fopen`, not use it everywhere. Folk should have options. Give them the URL to the PHAR (people know how to download files themselves without PHP being required) and put the `I can't run it!` diagnosis script somewhere to be downloaded and inspected. Actually check the Composer Installer - only a tiny part of it is checking code, the vast majority is about downloading one file and enforcing TLS while doing it.

This also solves the "I don't support openssl, or curl, or any feasible means of securely downloaded files in PHP issue"...which apparently is all too common. I honestly find it unconscionable to remove security for everyone, just for the sake of some folk with broken PHP configurations largely on Windows. It's very obviously the wrong approach to the problem - bad security should never be tolerated.

As @ircmaxell noted, TLS is just one part of the solution. The other is package signing and such. For PHARs you can both use GPG and PHARs natively support signing with a private key via openssl as another alternative. It's assumed that the signing key is kept offline. Humbug has been signed since I put the first PHAR online. It works just fine, and I can perform self-updates with signed packages without any issues at all.

There's be hell to pay if I lose the private key, of course :).

**Comment by javiereguiluz** [comment]
@padraic I'm afraid that the use of the installer is out of question. We just have to improve it as you and others suggested. To do so, we just have to find a smart person which can solve this problem meeting the stated requirements :)

**Comment by weaverryan** [comment]
@javiereguiluz I'm not convinced yet - I consider @ircmaxell and @padraic to be that level of smart person, but even they are able to highlight issues, but not give fool-proof solution. My worry is that if the situation is so complex, that it'll always either need to be insecure or buggy.

Let's focus only on SSL first, to see if that's feasible. Options:

A) Do what Composer does. curl works for Unix and *most* users can use `fopen`, but not all: http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen. So, Windows users without URL support for fopen would have problems. And I don't believe that `readfile` supports SSL. I think (?) this is why Composer has the installer

B) Do what Laravel does - download the installer via Composer (I realize this doesn't meet the above requirements - but I'm covering realistic bases) into your global directory.

C) Have people download the installer via a URL (i.e. in their browser). We could still have it self-updateable, but over SSL (and could give a clear error if that didn't work).

D) Have people download the project as a zip file, then have them run a script (could be a very short path) to start the "installer", which can do system checks and other setup.

Thoughts?

**Comment by javiereguiluz** [comment]
I think we should wait for Composer to solve this problem and then copy their solution.

**Comment by javiereguiluz** [comment]
@weaverryan I think I understand you now. You are talking about checking the integrity of the installer file. But I was talking about that *and* checking the integrity of anything that the installer downloads.

As far as I know, Composer doesn't check the integrity of the downloaded packages. So let's wait to see how they fix this security problem and then we'll copy the solution.

**Comment by xabbuh** [comment]
@javiereguiluz What is currently keeping us away from offering TLS for the installer download?

**Comment by javiereguiluz** [comment]
@xabbuh there are some reasons that sadly I cannot comment in public.

In any case, please let's focus on the main problem: Composer downloads more than 60 million packages each month ... and they seem to not verify the integrity of any of them. What can we do to help them solve this security problem? Is there any developer working on a solution we could copy? Thanks.

**Comment by padraic** [comment]
There have been enough comments by now to summarise. Beyond this, it's just circling around impossible requirements for the next ten years in search of a magic bullet that never materialises.

1. Download stuff over TLS/ Get a TLS certificate

If you limit the options to make this impossible, then you either cannot achieve this goal or are refusing to achieve it. To be blunt, the solutions are many, documented, and implementable in PHP, so anyone with a few spare hours can just do it already. Openssl, curl, command line offloading (wget, curl, powershell Invoke-WebRequest, etc), replace the installer with direct downloads allowing browser usage....pick one. You can even pick all of the above.

After there's an actual HTTPS URL, of course ;). Once there is, failure to implement the above becomes a security vulnerability awaiting assignment of a CVE ID.

2. Verify integrity, i.e. published by known entity.

Publish a signature. PHAR's support openssl signatures with a public/private RSA keypair. At minimum, publish the GPG signatures. Both are well documented methods. I prefer the openssl approach because it's automatically checked by PHP when using the PHAR, which means that everyone not willing to do manual checking will still benefit without lifting a finger.

3. Tell people with broken PHP installs to fix them and/or point them to direct downloads.

Many of the limitations and objections raised are due to a requirement to support people with insecure PHP installs. However, supporting them comes at the expense of quite literally forcing insecure solutions as the sole option on everyone else who do have working PHP installs which are more than capable of supporting TLS. The priorities in this scenario are misplaced.

We are effectively debating how to get PHP to download a file from a HTTPS url in an acceptably safe manner. It's bit silly.

**Comment by xabbuh** [comment]
Did anyone try https://github.com/padraic/phar-updater? Is it something that could be useful here?

**Comment by padraic** [comment]
@xabbuh It's eliminated by the requirement not to depend on openssl (which is required for TLS in PHP streams such as when using file_get_contents(), fopen() or readfile()).

**Comment by xabbuh** [comment]
I suggest to rethink about this requirement again. At least, offering such a solution for users of properly configured systems should be taken into account. We can then fall back to the current solution if OpenSSL is not available and show a large warning to the user.

**Comment by xabbuh** [comment]
I suggest to rethink about this requirement again. At least, offering such a solution for users of properly configured systems should be taken into account. We can then fall back to the current solution if OpenSSL is not available and show a large warning to the user.

**Comment by raulfraile** [comment]
I totally agree with @xabbuh, at this point and given all that has been said, it's clear that is not easy to have the perfect solution, but we should try to get at least a bit closer. 

@javiereguiluz Composer does not check the integrity of the downloaded packages, but 1) the composer binary is installed via HTTPS, 2) json files for providers are downloaded via HTTPS from packagist (AFAIK, correct me if I'm wrong) and 3) packages are downloaded from GitHub via HTTPS. I think we should have the same level of security.

**Comment by padraic** [comment]
@raulfraile Composer enforces TLS in the installer (has done for about a year now), but not in the main application - the PR for it has since fallen well out of date. This is biting a few other tools which have taken to extending or reusing Composer HTTP/Download classes without considering the TLS problem.

The Composer Installer itself therefore requires openssl. The main issues have been Windows users (who can enable it) and misconfigured systems (where the file containing trusted CA certs needed to be configured/installed). You can check through the Installer issues for `SSL` to see what issues cropped up.

**Comment by javiereguiluz** [comment]
Even if this can make all of you think that I'm a jerk, let me add an honest comment about all this:

According to symfony.com website, there are around 300,000 Symfony developers in the world. According to GitHub history, around 3,000 developers have contributed code and docs to Symfony. So here we have the magic 1% - 99% gap.

The truth is that everybody commenting in this thread belong to the 1%. We are the elite of the Symfony developers: our dev machines are perfectly configured and we care about important things, such as security.

But the real world is dominated by the other 99% of developers. A lot of them use Windows and can't use OpenSSL because of how they installed PHP. Some of them, as cleverly pointed by @padraic, have misconfigured systems which cause CA certificates problems.

Although I appreciate (and agree with) the opinions of people like @raulfraile and @xabbuh, we can't consider them because they are not representative of what's happening out there. You are part of the 1% (and I admire both of you for that) but we develop for the 99%.

What we can do, and we're going to do, is to gradually improve the security of the installer. For example, soon we'll enable HTTPS on symfony.com (finally!).

PS: by the way, Composer may be not as secure as we think. For example they have a Remote Code Execution Vulnerability [reported since 2012](https://github.com/composer/composer/issues/1074) and it's still not fixed. They even celebrated [its second anniversary](https://github.com/composer/composer/issues/1074#issuecomment-37229167) with some cake.

**Comment by padraic** [comment]
The real world doesn't require leaving anyone, not even a subset of misconfigured installs, subject to a security vulnerability. For each and every hurdle, there is a relatively simple solution of some type. With respect, playing up the ignorance of some subset of PHP programmers does not absolve you of the responsibility to rectify this.

Neither does pointing at Composer to provide safety in numbers - their issue has them banned off live servers (if you're aware of it) and drew the attention of a pool of programmers to create the solution which finally made it into the Composer Installer, and helped generate enough attention that it motivated, in part, an overhaul of TLS support in PHP 5.6. I'll be taking another crack at Moby Dick some other time ;).

So let's not join Composer, please. This is Symfony, a project with a stellar security record, a great Security Policy, and a practice of responsible disclosure up to requesting CVE IDs yourselves. I'm not familiar with how well linked the Installer is to the project as a whole, but I don't expect to see Composer copied.

You're looking for a one size to fit all download solution, and you're not going to find it. It doesn't exist. At some point there'll be a decision to enforce TLS and report an error, or decline to do so and not enforce TLS. The second option is a reportable security vulnerability. You solve it by making a best effort. If that fails, document it well and show users how to resolve problems. If that fails, there is the final resort - turning off TLS at the user's request (not automatically, e.g. a --disable-tls flag as proposed for Composer) and even then preceding output with a big red warning block about what disabling TLS means so there's no confusion on the part of users that are now officially off script.

At that point, you will have fulfilled your responsibilities. Probably. ;)

**Comment by WouterJ** [comment]
What about implementing https://github.com/padraic/phar-updater?

**Comment by Pierstoval** [comment]
+1 for @WouterJ , as of [Phar Updater](http://blog.astrumfutura.com/2015/06/self-updating-phars-stable-phar-updater-packages-now-available/) has updated to a stable version recently!

**Comment by mbrig-co** [comment]
Please help with me after successfully installing the Symfony according to the instructions in its website, when I run the comman `symfony new my_project` it returns the following Guzzle exceptions:

```
user@linux-cdf0:/srv/www/htdocs> symfony new my_project

 Downloading Symfony...
                                                    
  [GuzzleHttp\Exception\RequestException]                                          
  No system CA bundle could be found in any of the the common system locations.    
  PHP versions earlier than 5.6 are not properly configured to use the system's    
  CA bundle by default. In order to verify peer certificates, you will need to     
  supply the path on disk to a certificate bundle to the 'verify' request          
  option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do not   
  need a specific certificate bundle, then Mozilla provides a commonly used CA     
  bundle which can be downloaded here (provided by the maintainer of cURL):        
  https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. Once    
  you have a CA bundle available on disk, you can set the 'openssl.cafile' PHP     
  ini setting to point to the path to the file, allowing you to omit the 'verify'  
  request option. See http://curl.haxx.se/docs/sslcerts.html for more              
  information.                                                                     
                                                                                                                                              
  [RuntimeException]                                                               
  No system CA bundle could be found in any of the the common system locations.    
  PHP versions earlier than 5.6 are not properly configured to use the system's    
  CA bundle by default. In order to verify peer certificates, you will need to     
  supply the path on disk to a certificate bundle to the 'verify' request          
  option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do not   
  need a specific certificate bundle, then Mozilla provides a commonly used CA     
  bundle which can be downloaded here (provided by the maintainer of cURL):        
  https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. Once    
  you have a CA bundle available on disk, you can set the 'openssl.cafile' PHP     
  ini setting to point to the path to the file, allowing you to omit the 'verify'  
  request option. See http://curl.haxx.se/docs/sslcerts.html for more              
  information.                                                                     
                                                                                   
new <directory> [<version>]
```

So what I have to do to work Symfony installer perfect for me?

**System** => Linux (OpenSuse Leap 42.1 x86_64)
**PHP Version** => 5.5.14
**Registered PHP Streams** => php, file, glob, data, http, ftp, compress.bzip2, https, ftps, compress.zlib, zip, phar
**Registered Stream Socket Transports** => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls
**OpenSSL support** => enabled

I don't know what else is needed.

**Note:** I did it by using Composer `composer.phar create-project symfony/framework-standard-edition` and it worked perfectly for me and downloaded Symfony 3.0.1

Thanks in advance,
Muhammad Nasir Rahimi

**Comment by johnpancoast** [comment]
I was looking to see if symfony provided checksums of the installer and happened to find this issue, however, it has a lot of discussions about a lot of things you're planning.

stof mentioned we have the [checksums](https://github.com/sensiolabs/checksums/tree/master/symfony/symfony-installer) but they're out of date from what I can tell. The installer is currently on v1.5.0.

**Comment by xabbuh** [comment]
@javiereguiluz Are you able to publish the checksums too when you create new releases?

**Comment by javiereguiluz** [comment]
@xabbuh in theory yes. In practice, at the moment, no. In the future, yes again.

**Comment by johnpancoast** [comment]
:+1:

**Comment by olberger** [comment]
@johnpancoast Just filed https://github.com/sensiolabs/checksums/issues/5 for that.

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because now that [Symfony Flex](https://github.com/symfony/flex) replaces the Symfony Installer, we won't add new features to the installer. Thanks for understanding it.

**Comment by wouterj** [comment]
Wow, not even a security leak like this?
