### ISSUE TITLE
.gitignore sync

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony-installer#211]
I wonder why the installer have to recreate the `.gitignore` file instead of using the one provided in the `symfony/standard-edition` ?

The [build script](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/bin/build.sh#L51) used to create the archive remove the `.gitignore` file. But it'll certainly be easier to maintain if was kept if the line was slightly different:
```diff
- rm -rf app/cache/* app/logs/* .git*
+ rm -rf app/cache/* app/logs/* .git/
```
_(Also I'm not sure `cache` and `logs` directories should still be removed ?)_

[This method](https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/DownloadCommand.php#L310-L353) could then be removed. Currently, the generated `.gitignore` file for 3.0 for instance is not in sync with the latest changes:

```diff
1a2
> /bin/
3,6c4,7
< /phpunit.xml
< /var/*
< !/var/cache
< /var/cache/*
---
> /composer.phar
> /vendor/
> /web/bundles/
> /var/
8,9d8
< !/var/logs
< /var/logs/*
11,12d9
< !/var/sessions
< /var/sessions/*
14,16c11
< !var/SymfonyRequirements.php
< /vendor/
< /web/bundles/
---
> /phpunit.xml
```

**Comment by Pierstoval** [comment]
:+1: for this, the gitignore is already provided by the builder.
 
But it needs a new Symfony release for this :D

**Comment by ogizanagi** [comment]
@Pierstoval : Not necessarily. Can't it be a new installer release only ? (And recreating an archive containing the `.gitignore` file for each maintained Symfony versions)

**Comment by Pierstoval** [comment]
It would need a Symfony Standard release because the build script generates the tarball which contains the "built" datas, so the `.gitignore` file is not present now, but would be if the script is updated and a new version is released (because tarballs are pushed to `get.symfony.com` on each release).
It's not the installer that removes the `.gitignore` file :)
 
I don't know if the Symfony team can (or would) execute manually the tarball builder script, but actually I wonder if we could find a workaround in the installer, for instance download the `.gitignore` from github raw files in the `DownloadCommand`...

What do you think?

**Comment by ogizanagi** [comment]
Personally, I feel like using a workaround in the installer would be useless, whereas updating the build script and the archives (and I mean recreate them through the updated script, of course) would be way more reliable.

I don't see the issue about regenerating the tarballs, but of course, I might not know all the implications behind :)

**Comment by xabbuh** [comment]
Can we close here given that this must be fixed in the SensioDistributionBundle (see sensiolabs/SensioDistributionBundle#246)?

**Comment by ogizanagi** [comment]
Sure I think we can close it. Plus the new version of the installer now provides a workaround to keep the `.gitignore` files in sync, so having this issue opened doesn't make sense anymore.
