### ISSUE TITLE
Drop of 2.7 in symfony.com/versions.json after 2.8 release

### ISSUE THREAD

**Issue by Haehnchen** [symfony/symfony-installer#224]
I dont which project is responsible for this file. so a try ;)

`installable` of `http://symfony.com/versions.json` is used by PhpStorm Plugin for building a list of installable symfony-installer projects. Since 2.8 release 2.7 is missing in json.

issue: 
https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/643

![symfony-installer](https://cloud.githubusercontent.com/assets/1011712/11720180/73044ec8-9f5e-11e5-9d9d-8deb2a9c39c4.png)

**Comment by Pierstoval** [comment]
Yep this is strange... ping @lyrixx or @javiereguiluz maybe?

**Comment by javiereguiluz** [comment]
@Haehnchen thanks for reporting this issue. Originally we used this `versions.json` to check if a Symfony version was able to be installed via the Installer. Now that all newer versions are installable, we lost interest in `installable` option (only `non_installable` option is useful for the installer).

In any case, your message has made me realize about other use cases. So this error is now fixed and it will be available after the next server deploy. Thanks!

**Comment by Haehnchen** [comment]
:thumbsup:

**Comment by xabbuh** [comment]
@javiereguiluz Do you know how often there are deploys?

**Comment by javiereguiluz** [comment]
This issue should be fixed by now. http://symfony.com/versions.json now displays all the installable and non-installable versions.

**Comment by Pierstoval** [comment]
@javiereguiluz I'm surprised to see no reference about the 2.5 branche in either `installable` and `non_installable`... Is 2.5 an installable version or not?

**Comment by stof** [comment]
@Pierstoval Looks like installable does not list unmaintained branches.

In any case, there is strictly no reason to create a new project based on 2.5.

**Comment by javiereguiluz** [comment]
@Pierstoval nice catch! This is indeed a bug. the `installable` option should display all the Symfony versions which are installable by the Symfony Installer, no matter if they are maintained or not.

This issue has been fixed and it will be available soon.

**Comment by stof** [comment]
@javiereguiluz would it make sense to expose the list of maintained versions in versions.json too ? IDE integrations should only allow creating new projects based on maintained versions for instance IMO.

**Comment by javiereguiluz** [comment]
My question is: maintained versions are only the most recent patch version of the maintained branches? E.g. 2.3.35 is maintained but 2.3.34 is not?  This may be confusing because strictly speaking 2.3.35 is not maintained. If we find and error, it will be fixed in the (non-existent) future 2.3.36 version.

**Comment by stof** [comment]
@javiereguiluz I would not give release versions, but branches (e.g. ``2.3``, ``2.7``). The installer already allows specifying a branch rather than an exact release, and the versions endpoint allows IDEs to do the same if they bypass the installer (as they give the latest release for each branch).

Users should only specify a minor version all the time IMO. It does not make sense to ask them to choose which patch release they want to use for their new project (they should always use the latest one)
