### ISSUE TITLE
Use padraic/humbug_get_contents in self-update command

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-installer#228]
Now that the installer can be downloaded using HTTPS, we should consider provide more secure ways to perform updates. One change I would like to see is to use the `humbug_get_contents()` method from the [padraic/humbug_get_contents package](https://github.com/padraic/file_get_contents) as a replacement for `file_get_contents()` to get update archives from the symfony.com server.

**Comment by javiereguiluz** [comment]
In theory this package looks great. In practice I'm worried about this:

> In rare cases, this function will complain when attempting to retrieve HTTPS URIs:
> [...]
> A valid cafile could not be located, i.e. your server is misconfigured or missing a package
> [...]
> This is not a justification for disabling SSL/TLS [...] Resolve such errors; don't ignore or workaround them.

In my experience, it's incredibly common to have a wrong certificate file in your computer (or having wrongly configured its path in PHP). This package proposes to fail hard in those situations. I strongly disagree because that means it would fail for people who need the Installer most.

**Comment by xabbuh** [comment]
Well, we could then still display a big warning and display a dialog that offers the user the possibility to download the installer through a plain HTTP connection. That way we do not teach them that it is okay to simply use untrusted encrypted connections.

**Comment by weaverryan** [comment]
I agree with @xabbuh. Unfortunately, I think this is a case where we need to sacrifice some usability due to security. I might go further: not ask them if they want to use http, but instead print out the URL they should use to download the file via their browser (the https version of the URL) with instructions on what to do after that (e.g. find the file and run "php installer" or whatever it is). I'm a bit concerned about symfony catching hell for their installer being insecure if we keep the status quo.

**Comment by javiereguiluz** [comment]
Just to add another point of view here: if we download a minuscule open-source application over HTTP, we are opening a huge security hole. But, if we download, install and use closed-source applications over HTTPS, everything is fine. Please look at your own computers: they are all full of closed-source applications. And all of us happily use them: what about their trojans? backdoors? privacy violations? suspect behavior? We don't care.

**Comment by javiereguiluz** [comment]
In any case, to be clear: I mostly agree with you. The only difference is that if HTTPS doesn't work, I'd just display a warning message and I'd continue downloading it via HTTP.

**Comment by xabbuh** [comment]
I can live with either solution as long as we do not teach our users that they do not have to care about their security configuration. If they don't care about configuring HTTPS and the related stuff properly, they will also not have any issues with just using HTTP.

**Comment by javiereguiluz** [comment]
I'll leave here [this reference](https://bugzilla.mozilla.org/show_bug.cgi?id=1064387#c6) that shows how Firefox lost more than 1 million downloads after "doing the right thing" (from a security point of view) and dropping "the insecure SHA-1 certificate" from their site. They quickly reverted this decision and maintained the "insecure" certificate.

This example illustrates my point: if the Symfony Installer doesn't work flawless whatever the user setup, then it's useless. That's why I don't like the idea of making the installer work only if the user setup is completely secure

**Comment by xabbuh** [comment]
There is one big difference imho: Firefox is used by "everyone". So must of the time when people using it don't care about security, they first hurt themselves. But, people using Symfony are developers. They **must** care about security and if they do not care about, for me that's no justification to not hurt them because we are doing it right. If they build insecure applications later on because of the "I don't care attitude", they don't only hurt themselves, but they hurt every user of their application.

And by the way, they would still be able to download the installer by using their browser. So it's not that they won't be able to get it at all.

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because now that [Symfony Flex](https://github.com/symfony/flex) replaces the Symfony Installer, we won't add new features to the installer. Thanks for understanding it.
