### ISSUE TITLE
Install as MicroKernel project

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony-installer#231]
We really like [the `MicroKernel` approach](http://symfony.com/blog/new-in-symfony-2-8-symfony-as-a-microframework) because that allows us to easily prototype without having to define a controller and environments. At the moment we remove all unused stuff from the standard edition manually, but it would be great if the installer would allow us to do this automatically (or step by step).

What about allowing to install `MicroKernel` via the installer, and let the installer ask for the following:

* to define routing via separate .yml file, or just add a single `index` route in `MicroKernel::configureRoutes`
* to only define the `dev` environment (so all other configuration files don't have to be generated)
* to define a controller, or only add `MicroKernel::indexAction` (so the entire /src folder isn't needed)
* to register the Twig bundle, and if so also add `/app/Resources/views/base.html.twig` and `index.html.twig`

This probably is enough to make most of the basic applications afterwards, and lowers the boundary for users that are new to Symfony because they will not be overwhelmed by all components and a complex folder structure.

**Comment by Pierstoval** [comment]
It's part of #39's discussion, I'd totally support the idea of creating a "MicroKernel edition" :+1:

**Comment by rvanlaak** [comment]
Was looking for exactly that, couldn't imagine that this didn't cross someones mind before :+1: 

That would be the `-e=microkernel` parameter, but would also be great if it would ask some extra questions to make the installation process even simpler.

**Comment by Pierstoval** [comment]
Yep but as said many times in other issues, before doing anything the @symfony/deciders must decide a solution upon managing Symfony editions. There are already Standard and Demo editions, there's also a Rest edition (which is not often promoted) and we can easily imagine any other edition, like the MicroKernel one.
 
But for this, a strategy must be decided because for Standard and Demo editions, you can download them by using a simple zipball built on SensioLabs servers automatically on each release, so a good strategy must be defined for "other" or "custom" editions.

**Comment by stof** [comment]
I agree with @Pierstoval. Creating a new project based on the micro-kernel needs to be done using an edition (with an archive the installer can download). Doing that by downloading the standard edition and then altering it would be a maintenance nightmare.
So we should first figure out how to deal with editions

**Comment by rvanlaak** [comment]
Yes, also agree with that :+1: wasn't able to find much information about these editions earlier so will close this issue.
