### ISSUE TITLE
Remove pre-configured platform PHP version

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-installer#234]
Starting with symfony/symfony-standard@d0e9308e807aae02c332897d610ad5eb49d81c1e, the Symfony Standard Edition will define the platform PHP version as 5.3.3 to avoid issues for people using older PHP versions than the system on which the downloadable packages are built. However, this will lead to weird behaviour for people who actually use newer PHP versions and want to install packages that are incompatible with PHP 5.3. So I think we should simply remove the platform PHP version configuration from the `composer.json` file after the installation has finished.

**Comment by Pierstoval** [comment]
@xabbuh I don't know but I'd suggest to add a warning/note to the user to force him to specify his own PHP version so it is consistent with his own machine and the potential deployment machine.
 
When I discovered this option I started putting it on every project because I have all versions installed on my machine, projects using different versions, my colleagues use other versions, and the different prod environments also have different versions.
 
I'm starting to think about this parameter as a mandatory one to keep consistency between code, and more, to be sure everything is working well.

**Comment by xabbuh** [comment]
@Pierstoval That's an option too. But in this case I suggest that we ask the user to enter the desired PHP version (we could offer to keep the current value or use the currently use PHP version too to make this step more user-friendly).

**Comment by Pierstoval** [comment]
I'm not in favor of asking the user to enter his version, not by opinion (I like the idea) but mostly because the installer was designed for the user to have no interaction with the terminal to enhance automatization of Symfony installation.
 
However, may we propose a command-line `--php-version=[PHP_VERSION]` option and another `--reset-php-version`?

**Comment by Tobion** [comment]
Maybe the installer should have preconfigured packages for each minor version of PHP. Then when a user does install symfony it choses the package based on the local PHP version. This way we would not need to hard-code the php version in composer.json and it will use recent and compatible versions for everyone.

**Comment by javiereguiluz** [comment]
Let's forget for a moment about the technical solution and let's discuss first about what we want to do.

In my opinion, this is the desired behavior. Let me know if you agree:

* When I create a project, the downloaded code is ready to be executed in the lowest PHP version required by that Symfony version (e.g.  5.3.9 for Symfony 2.8, but 5.5.9 for Symfony 3.0).
* When I create a project, I can do a `composer update` afterwards and it should upgrade all dependencies to my PHP version.

**Comment by Tobion** [comment]
The desired behavior to me is:

- When I create a project, it works.

> When I create a project, the downloaded code is ready to be executed in the lowest PHP version required by that Symfony version (e.g. 5.3.9 for Symfony 2.8, but 5.5.9 for Symfony 3.0).

This does not comply with above.

**Comment by xabbuh** [comment]
I do not fully agree. Yes, it is great that you now have a fully working application. However, we teach people not to blindly execute `composer update`. Thus, they will use something like `composer require package` and will be wondering why Composer refuses to install a certain package because of their PHP version (or silently installs an older version). By the way, even running `composer update` wouldn't get then more recent versions if they required more recent PHP versions (the platform config doesn't vanish).

**Comment by javiereguiluz** [comment]
@Tobion we have a very serious misunderstanding about this issue. In my opinion, it's the current situation which doesn't work. How to reproduce:

  1. My computer has PHP 5.3.9
  2. I execute `symfony new my_project 2.8`
  3. Nothing works because the installed Symfony 2.8 versions contains Doctrine libraries that use PHP 5.5 code.

**Comment by Tobion** [comment]
I know I created the issue: https://github.com/symfony/symfony-standard/issues/858
Please read it.

**Comment by Pierstoval** [comment]
@Tobion I think it's impossible to have multiple Symfony zipballs depending on PHP version, it would be very cumbersome to do on the SensioLabs server, and pretty useless if finally we notice that something like >95% of downloaded versions are 5.5+.
Plus, it's also heavy to propose a "table" of symfony branches to download depending on php versions, like this:

| PHP / Symfony | 2.3 | 2.8 | 3.0 |
|-------------|:---:|:----:|:----:|
| 5.3           |  x  |  x  |  x  |
| 5.4           |  x  |  x  |  x  |
| 5.5           |  x  |  x  |  x  |
| 5.6           |  x  |  x  |  x  |
| 7.0           |  x  |  x  |  x  |

This would be a pain ton maintain and to store on the servers.
 
I once proposed on symfony/symfony-standard#858 to update the build script in SensioDistributionBundle so it is executed with PHP5.3 for the `2.x` branches and php5.5 for the `3.x` branch. The problem is that it sounds impossible.
 
So @fabpot's final decision is the best to me: install the dependencies with lowest compatible versions first, and let the user do his `composer update` with his own `config.platform` parameter so he can do whatever he wants.

**Comment by javian** [comment]
@javiereguiluz The installer requires PHP 5.4 does it not ?

**Comment by javiereguiluz** [comment]
@javian yes, but there are still some people installing Symfony with Composer, so they may use PHP 5.3.

**Comment by xabbuh** [comment]
see #236
