### ISSUE TITLE
Can't install latest 3.2 version

### ISSUE THREAD

**Issue by gregurco** [symfony/symfony-installer#301]
Hello.
When I run next commands:
```bash
$ symfony new project_dir 3.2
$ symfony new project_dir 3.2.14
```
I receive next error:
```
[RuntimeException]                                                            
The selected version (3.2.14) cannot be installed because it does not exist.  
Execute the following command to install the latest stable Symfony release:   
/usr/local/bin/symfony new 3.2      
```
Version 3.2.14 is the latest in 3.2 and it's installable: http://symfony.com/versions.json
It's ok, if I install 3.2.13 (previous version).
I debugged it a little bit I found that installer tries to download from next link: https://get.symfony.com/Symfony_Standard_Vendors_3.2.14.tgz and as you can see there is **Access Denied** error.

Installer version: 1.5.9 (latest).

Thanks.

**Comment by javiereguiluz** [comment]
@gregurco I've asked about this and I've been told that this Symfony 3.2.14 package won't be built because Symfony 3.2 is no longer supported for bug fixes (only for security fixes until January 2018). The solution should be to use 3.3 or 3.4 version (or better 4.x, if that's possible for your project). I'm sorry!
