### ISSUE TITLE
Problems to install symfony using installer behind a proxy

### ISSUE THREAD

**Issue by MarlonAEC** [symfony/symfony-installer#316]
I've been trying to install symfony behind a proxy, and the installer finishes and tells me that it can't continue and doesn't install ... I've tried setting up the environment variables like this:

`set http_proxy=http://user:password@proxy_address:port`
`set https_proxy=http://user:password@proxy_address:port`

I have also configured git to use the same proxy

`git config --global http.proxy http://user:password@proxy_address:port`

but it still doesn't work. I have also tried installing symfony using composer without the installer:

`composer create-project symfony/website-skeleton my_new_project`

and it works perfectly!! but I would like to know what I need to do to make the installer work correctly... any tips?? :( Regards!!

well some update... I have found that in windows there is another proxy for the system and I have configured it using the command:
`netsh winhttp import proxy source=ie`
that import the internet explorer proxy settings... well this works!! the installer start to download but after 4 sec the installer get some error 403 (I have understood that this is related to forbidden access), I run the installer as an administrator and it didn't work either.. :( 
i have also tried using the command:
`php -r "file_put_contents('symfony', file_get_contents('https://symfony.com/installer'));"`

but I get this error:

`PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in Command line code on line 1`
`Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in Command line code on line 1`
`PHP Warning:  file_get_contents(http://symfony.com/installer): failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.  in Command line code on line 1`
`Warning: file_get_contents(http://symfony.com/installer): failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.  in Command line code on line 1`

really i need some help please!!! :(

**Comment by javiereguiluz** [comment]
@MarlonAEC I'm afraid that this installer was abandoned a few months ago and it's no longer recommended to use it.

Instead, we have a new installer, more modern and with many more features, that will probably work for you. First, you install it once as explained in https://symfony.com/download  and then you can use it to create apps as explained in https://symfony.com/doc/current/setup.html

I'm closing this issue because we no longer update the old installer, but if you have any issue using the new installer, please create an issue here: https://github.com/symfony/cli/issues  Thanks!
