### ISSUE TITLE
Allow to install more Symfony distributions, not only the standard edition 

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-installer#39]
_(original idea proposed by @loostro in https://github.com/javiereguiluz/symfony-toolbelt/issues/17)_

Just an idea that crossed my mind.

Updated to summarize the discussion:
- use short edition names
- version number is optional and defaults to latest stable version (of that edition)
- argument name in 2 versions; verbose `--edition` and shortened `-e`

Syntax:
`symfony new [dir] (optional [version], optional [edition])`

Examples:

| Command | edition | version |
| --- | :-: | --: |
| `symfony new blog/` | symfony-standard-edition | latest stable (*) |
| `symfony new blog/ 2.2.5` | symfony-standard-edition | 2.2.5 |
| `symfony new blog/ -e=rest` | symfony-rest-edition | latest stable (*) |
| `symfony new blog/ --edition=rest` | symfony-rest-edition | latest stable (*) |
| `symfony new blog/ 2.2.5 -e=rest` | symfony-rest-edition | 2.2.5 |
| `symfony new blog/ 2.2.5 --edition=rest` | symfony-rest-edition | 2.2.5 |

(*) - for that edition

**Comment by loostro** [comment]
@javiereguiluz I'd like to prepare symfony2 admingenerator edition. Where do I start?

**Comment by Pierstoval** [comment]
As long as we rely on the `versions.json` file to check the different version types, I'd recommend that every registered edition has its own `versions.json` file following the same syntax as the standard edition.
 
I think that registering a Symfony edition might be good for anyone, but maybe each edition needs to be validated by the Symfony team, so maybe we can think about creating some bundles and APIs to allow anyone to create and register a Symfony distribution ? 
 
What I'm talking about may be a very big issue and might need hard work, but I think that any Symfony distribution might be a fork from the standard, which adds/removes dependencies, updates the config file, adds one vendor in the `src` dir, and some assets, so a "rebasing-like" process may be a good point in "validating" a Symfony distribution ?
 
Ok, maybe too complex :laughing: :laughing:

**Comment by loostro** [comment]
The admingenerator edition would be just some additional dependencies + modified demo bundle (instead of AcmeDemoBundle, we'd have AdmingeneratorDemoBundle).

**Comment by Pierstoval** [comment]
The AcmeDemoBundle will leave the standard edition soon, IIRC

**Comment by loostro** [comment]
We could move the AdmingeneratorDemoBundle to a seperate repository and just add a suggestion to `composer.json`, to follow the same pattern as symfony standard edition.

**Comment by Pierstoval** [comment]
Maybe the best solution for you is to have a single bundle with a very good documentation, like there is on `SonataAdminBundle` and `EasyAdminBundle` ?
 
I don't know if a whole distribution is relevant, because in fact an admin generator can be used for many types of "distributions" : an ERP back-end or a CMS for instance. 
 
Your bundle is good enough to stay "standalone".
 
A new edition sounds more to me like an enhanced/reduce the features on the standard-edition. REST, CMF and Demo are the actual other Symfony editions, and I Think that a proper politics about editions must be debated before talking about "how to implement the other editions" :)
 
What do you think of these ideas @javiereguiluz ? ping @fabpot ?

**Comment by javiereguiluz** [comment]
I agree that we should talk seriously about Symfony editions and decide what to do about them in the future.

**Comment by loostro** [comment]
To me the symfony installer and diffrent distributions are a chance to make it easier for new developers to bootstrap (and try out) what Admingenerator project has to offer.

Actually I believe it would benefit the whole community if you could easily start `new admingenerator-edition`, `new sonata-admin-edition` or `new easy-admin-edition`. Some developers are given enough time (and money) to look for the best solution. Most of us don't. Being able to quickly check diffrent distributions, the benefits and pitfalls, would be a very strong point for symfony ecosystem IMHO.

Also that would also be a chance to attract more developers to the project, which (I hope) would bring more PR's and help us improve it's quality.

Anyways I'm looking forward to hear what @fabpot @javiereguiluz think about that.

**Comment by javiereguiluz** [comment]
@loostro I agree with you and, as you've seen, editions are on our minds since first day of the installer. And I'd also love to have a 1-command solution to test drive cool bundles such as AdminGenerator.

My only concern is that editions have never really been promoted actively and it's a somewhat "strange" thing inside the Symfony community. That's why I said that we need to seriously think the strategy to follow for the editions.

**Comment by Pierstoval** [comment]
@loostro you're totally right about the editions you propose, and I think the three admin ones you are talking about are totally relevant, because each one has its strengths and weaknesses (if we can say they have weaknesses :smiley: )
 
But the first point of that all is to choose how the editions will be promoted in the Symfony community.
New sub-site for Symfony ? Docs ?
And how are we gonna list the editions ? Is it only a simple list of some interesting symfony/standard-edition forks on Github ? 
Is there going to be a specific channel to register an edition in order to appear on the Symfony's website ? If so, what will be the API to create a Symfony edition ? Will the editions have to be validated by the Symfony team, or will "we" list them all and only order them by "starring" or "rating" ?
 
And also, will a Symfony edition be make-able for companies ? I know that MANY companies are using Symfony standard edition, and many of them use their own bundles or packages, some public, some private, and add them for each new project, so we may imagine an "easy" solution for companies to create and update their distributions automatically for each new Symfony release, etc.
 
I think that all these questions might need an answer before thinking about adding our beloved `--edition` argument in Symfony installer, but as I'm not in the team and I'm just a huge fanboy, I'm not the decision maker :laughing:

**Comment by loostro** [comment]
Well, I believe first and most importaint point is the license. Symfony2 is MIT, so any official distribution should also be MIT-licensed. I understand that @fabpot would probably want some quality/security control over bundles/editions promoted. I can only speak for Admingenerator team - if there were any official prerequisites we would do our best to meet all of them. We're also open to invite symfony2 core members to admingenerator team - I believe that could only improve the quality of our project.

How to list the editions? Well, to me it does not matter so much. It can be in symfony2 docs, or a seperate page, or a channel. Thats not an issue.

How to decide "which one goes first"? Again, I don't see this as a popularity contest, so I don't mind. Let Sonata & EasyAdmin go first, no problem. All I care is "how can we make the process of bootstraping/trying out admingenerator simpler/easier, especially to new developers?". So I'm OK with whatever solution @fabpot would propose :)

**Comment by Pierstoval** [comment]
IMO there are not that many prerequisites to fit perfectly to Symfony:
* Proper phpunit testing with high code coverage and on multiple Symfony and PHP versions
* Respect the Symfony and PSR coding standards
* 4 star on SensioLabs-Insight maybe
 
"My" distribution would be a CMS one, based on the features implemented on many other CMS, in order to have a Symfony-standard-compatible CMS skeleton/project, which will be really different than the new Drupal using Symfony components (which has its own API

**Comment by Pierstoval** [comment]
I was thinking about something...
 
At the moment we can only download the standard edition.
 
Maybe we can provide a quick-hack solution to propose users to create their own installer for their distribution ? In fact, the installer is just a phar file, so if you want a custom distribution, you can `box build` your own fork and provide custom datas inside the `NewCommand`.
 
Maybe we could provide something like a new `NewDistribution` or `Distribution` command which would be easily configurable with a simple php file at the root of the installer. If this file does not exist, we use default params. And if it is, we we set it as the command parameters for the url and it can download any symfony file from any host. It's a quick-hack to avoid creating a whole class whenever you want a new distribution.
 
But obviously, it's only good until we make a real decision on how to manage distributions in the future...

**Comment by ogizanagi** [comment]
What about allowing to register custom editions by using a `SYMFONY_EDITIONS_JSON`
 env var (or whatever name it is) in order to load a json file describing where to find those editions ?

Then, editions maintainers only have to state in their README.md how to register the edition. (A command might be available in symfony installer in order to do that easily.)

Of course, we could provide a base `editions.json` file in `symfony/symfony-installer` in order to promote some editions.

Adding an edition might looks like:
```json
# ~.symfony/editions.json

{
   [...]
   "fos-rest-edition": {
        "url": "http://get.symfony-rest-edition.fos.fr/download?v={version}",
        "alias": "rest",
        "available-extensions": ["tar", "zip"]
    }
}

**Comment by Pierstoval** [comment]
I don't think that an environment var is good. A distant "repository" should be better, because a Symfony edition is nothing more than a "pre-compiled" Symfony app. 
 
Using an env var and/or a `json` file would be "user-specific".
The goal of the installer is to be like "plug-and-play": you run the command, Symfony is installed, whatever edition you chose.
 
Even if it sounds risky, and if it looks similar to phpBB MODs system, I think a "procedural" system can be used.
I mean, an edition might be a `yml` file with many configurations, for instance:

```yml
symfony_edition:
    name: my-vendor/my-cms-edition
    projects_dependencies: # Projects to checkout from some kind of repo
        "src/": # Install them in "src" directory
            # May clone from git directly
            - "git@github.com:MyVendor/MyAwesomeCmsBundle" 
            # Or may download from packagist with a tag
            "my-vendor/my-cms-bundle": "~1.0"  
    files_to_update:
        "app/config.yml":
            add: |
                Config that has to be appended (keeps the old config file)
            merge: |
                Merge these parameters, so the whole file can be rewritten
            remove: |
                Parameters to remove
    composer_dependencies:
        add: 
            "friendsofsymfony/user-bundle": "~1.0" # adds the repo with "composer require"
        remove:
            - "symfony/assetic-bundle" # Will "composer remove" the dependency
``` 

It's totally raw and not entirely thoughtfully made, and it's in YAML, but then it will "start with the standard edition", and then update it with all the parameters specified, like in phpBB MODs: `Find file app/AppKernel.php | Look for line containing "registerBundles" | After line, add "..."`.

We can also use Composer, by specifying a `type: "symfony-edition"` and being forced to add an "extra" field with the name of the class that has to be executed in order to make all the modifications in the Standard Edition (would be cleaner and more flexible, I think).

With this kind of system, the only things to do in the installer is to:
* Install Symfony
* Download the config file from packagist with the name `my-vendor/my-cms-edition`
* Apply the modifications

A bunch of continuous integration and statistics can be made with the Packagist API: look for all repos of type `symfony-edition`, or propose the users to add the editions themselves, and run a batch of tests to check the Symfony edition is "valid" or not. Needs a real new app for this, but hey, Symfony would be more awesome then :wink:

**Comment by ogizanagi** [comment]
It's only user specific for "unofficially validated" editions. The `SYMFONY_EDITIONS_JSON` env var is only to add more editions. I was also reacting to your comment:
> Maybe we can provide a quick-hack solution to propose users to create their own installer for their distribution ? In fact, the installer is just a phar file, so if you want a custom distribution, you can
box build your own fork and provide custom datas inside the NewCommand.

Validated editions would be registered in a `editions.json` file inside the Symfony Installer phar.

**Comment by Pierstoval** [comment]
I don't know how much env vars are used by developers, I personally never use them, except when I'm forced to do so, this may alter my judgement about the env vars (even for the installer, env vars about directory structure when installing with composer, or about the acme demo... I think env vars for this are bullshit...).
 
By the way, if the "validated" editions are inside the phar file, it can be good, but still, an "old" installer will be unable to install a brand new edition unless the dev updates it, and actually, there is no warning about this (contrary to Composer which throws an alert when the build is more than 30 days old).

**Comment by ogizanagi** [comment]
I might have forget to mention that the default for `SYMFONY_EDITIONS_JSON` env var would be `~/.symfony/editions.json`... :smile: 

Indeed, this system is very similar to what Composer does with the `COMPOSER_HOME` or `COMPOSER_CACHE_DIR` env vars for instance.

> an "old" installer will be unable to install a brand new edition unless the dev updates it, and actually, there is no warning about this (contrary to Composer which throws an alert when the build is more than 30 days old).

We can add this kind of check easily this is something really needed...But actually, I don't think it is. If you are unable to install a brand new edition, update the Symfony Installer or add the edition yourself if for any reason you need the old installer ??

**Comment by Pierstoval** [comment]
You're right, we can add this kind of message when "not finding" an edition.
And ok for the default `SYMFONY_EDITIONS_JSON` value, makes sense :)

**Comment by ogizanagi** [comment]
Lastly, I'll add that those suggestions are mostly solutions to get around the need to register editions on symfony.com and build downloads for them, with the benefit of providing a way to add custom editions ourself.

**Comment by Pierstoval** [comment]
It'd be better to have symfony.com promoting only, and have users creating their own distributions elsewhere, because right now you just have to fork the project, and create your own edition with a specific branch in packagist, or create an entirely standalone app (detached from the `symfony/symfony-standard` repo) put on packagist.
 
It's completely flexible, and still valuable as open-sourced.
 
I think Symfony should keep this, and the Symfony/Sensio team can simply promote its favorite (or personal) editions on their website

**Comment by ogizanagi** [comment]
The benefit of having promoted editions in the Symfony Installer repository instead of symfony.com is that adding them will be community-driven.

**Comment by rvanlaak** [comment]
As mentioned in #231 it would be great if the installer would support MicroKernel. That would lower the barrier to use Symfony for easy single file projects.

**Comment by Pierstoval** [comment]
Also, I would like to see a CLI Edition, a simple skeleton to easily create command-line applications with Symfony's console component.

**Comment by drgomesp** [comment]
Lots of people would love to have https://github.com/drgomesp/symfony-docker available for installation via the Symfony Installer. Is that somewhat possible?

**Comment by Pierstoval** [comment]
@drgomesp When the @Symfony team will take decitions on this subject, I bet it will :)

**Comment by javiereguiluz** [comment]
Closing this proposal as "won't fix" because newer Symfony versions no longer support distributions. Thank you all for the discussion.
