### ISSUE TITLE
Optionally install Composer

### ISSUE THREAD

**Issue by raulfraile** [symfony/symfony-installer#56]
As far as I know, the Symfony Installer has two main goals: speed and lower the entry barrier for beginners. As sooner or later the user will have to use Composer, It might be interesting that the installer optionally could take care of installing Composer too:

````
symfony new my_project --install-composer
````

It will be probably easier to just download the `composer.phar` file in the Symfony project, but there are ways to make the installation global.

What do you think?

**Comment by georgiana-gligor** [comment]
I would recommend taking a step-wise approach:
* let the main install command finish executing
* ask a question in the console, along the lines of "Would you like help installing composer too?"
* upon a positive answer, I would see a copy-pastable set of commands needed to accomplish that, tailored for the specific operating system the user is performing this into

**Comment by Pierstoval** [comment]
@georgiana-gligor The main improvement of the Symfony installer on composer was to get rid of the console prompts. The "old-way" was using `composer create-project`, and composer hooks were asking questions especially about the `parameters.yml` file for instance.
 
I'm -1 for this feature if you ask the user, because it would be a "rewind back in time" in one of the first goals of the installer.
 
That said, if the feature is accepted, I'd recommend to save the `composer.phar` file in the project's root directory, instead of globally, because of what @stof explained about global configuration.

**Comment by javiereguiluz** [comment]
Given the amount of `-1` votes on this proposal, let's close it for now as *won't fix*.

We'll reconsider this feature in the future, when we have more experience with the installer and more people use it and provide us their feedback.

Thank you all for the discussion!
