### ISSUE TITLE
[DX] improve updating/migrating existing symfony projects

### ISSUE THREAD

**Issue by tolry** [symfony/symfony-installer#62]
Correct me if I am wrong, but currently upgrading an existing project consists of changing composer.json manually and following the release notes (adding components to your kernel, making changes to web/app(_dev)?.php and so on).

It would be nice to have some kind of semi-automatic process to guide developers in this task. My naive approach would be to do this by implementing an "update/upgrade" command to the installer. If this is better placed in symfony/symfony, please feel free to move this (or I can do it).

There would be lot of room for improvement, e.g. adding new config parameters that became mandatory or even refactoring the code to comply to changes in the new versions or removing deprecated classes / functions / APIs / ...

Any ideas, suggestions, additions on this?

thx,
Tobias

**Comment by javiereguiluz** [comment]
@tolry I'm closing this issue because in its original form would complicate the installer a lot and it would requiere a lot of resources that we don't have at the moment.

However, I think you are right about the lack of information about how to upgrade Symfony applications. Thankfully, the great @weaverryan has created an issue to tackle this problem (see https://github.com/symfony/symfony-docs/issues/4172). We'l soon have this information as part of the official Symfony documentation.

**Comment by tolry** [comment]
@javiereguiluz yeah, I was afraid that this is too big a project for just a single issue. I will check the progress on the docs issue.

Thanks a lot for your time and feedback.
